internal_api_key=bd8014243ba2e2acdac6296d0c9f555ab13c2090f94e40a97a516042f99755c1
api_url=https://yoko.makii.net/api/outbreakjava/
servers_api=https://yoko.makii.net/api/servers/
gs_ip=144.22.36.255
db_user=
db_password=
